version: 2.1
orbs:
  node: circleci/node@3.0.0 

commands:
  bundle-install:
    description: "bundle install, with caching"
    parameters:
      key:
        type: string
        default: "v1"
    steps:
      - restore_cache:
         keys:
            - bundle-<< parameters.key >>-{{ checksum "./Gemfile.lock" }}-{{ .Branch }}
      - run:
          name: bundle install
          command: bundle install --path ./vendor/bundle
      - save_cache:
          key: bundle-<< parameters.key >>-{{ checksum "./Gemfile.lock" }}-{{ .Branch }}
          paths:
            - ./vendor/bundle
           

jobs:
  build:
    docker: 
      - image: cimg/ruby:2.7-node
    steps:
      - run:
        name: We need sqlite
        command: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      - checkout
      - bundle-install:
          key: "v1"
      - node/install-yarn
      - node/install-packages:
          cache-version: stringy-brisket
          pkg-manager: yarn
      - run:
          name: webpacker compile
          command: rake webpacker:compile
      - run:
          name: good morning database
          command: rake db:schema:load
      - run:
          name: run tests
          command: rake test
      - run:
          name: heroku deploy
          command: git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
