version: 2.1
orbs:
  node: circleci/node@3.0.0 

commands:
  bundle-install:
    description: "work dammit"
    parameters:
      key:
        type: string
        default: "crunchy"
    steps:
      - restore_cache:
         keys:
            - << parameters.key >>-{{ checksum "./Gemfile.lock" }}-{{ .Branch }}
      - run:
          name: tell Bundle to store its gems here
          command: bundle config set deployment 'true'
      - run:
          name: bundle install
          command: bundle install --deployment
      - save_cache:
          key: << parameters.key >>-{{ checksum "./Gemfile.lock" }}-{{ .Branch }}
          paths:
            - ./vendor/bundle
           

jobs:
  build:
    docker: 
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - run:
          name: Which rubygems?
          command: gem -v
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: We need sqlite
          command: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      - bundle-install:
          key: "butt"
      - node/install-yarn
      - node/install-packages:
          cache-version: stringy-brisket
          pkg-manager: yarn
      - run:
          name: webpacker compile
          command: rake webpacker:compile
      - run:
          name: migrations
          command: rake db:schema:load
      - run:
          name: run tests
          command: rake test
      - run:
          name: heroku deploy
          command: git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
