version: 2.1
orbs:
  node: circleci/node@3.0.0 

commands:
  install-deps:
    parameters:
      key:
        default: gems-v1
        description: The cache key to use. Change this to clear the cache
        type: string
    description: Install gems with Bundler. Except cache usefully
    steps:
    - restore_cache:
        keys:
        - << parameters.key >>-{{ checksum "./Gemfile.lock"  }}-{{
          .Branch }}
    - run:
        command: |
          bundle install --deployment
        name: Bundle Install That Might Cache usefully
    - save_cache:
      key: << parameters.key >>-{{ checksum "./Gemfile.lock"  }}-{{
        .Branch }}
      paths:
      - ./vendor/bundle

jobs:
  build:
    docker: cimg/ruby:2.7
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which rubygems?
          command: gem -v
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: We need sqlite
          command: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      - run:
          name: configure bundler
          command: bundle config deployment true
      - ruby/install-deps:
          key: chocoegg
          path: ./vendor/bundle
      - node/install-packages:
          cache-version: stringy-brisket
          pkg-manager: yarn
      - run:
          name: webpacker compile
          command: rake webpacker:compile
      - run:
          name: migrations
          command: rails db:schema:load
      - run:
          name: run tests
          command: rake test
