version: 2.1
orbs:
  node: circleci/node@3.0.0
  ruby: circleci/ruby@1.0.0 

jobs:
  build:
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which rubygems?
          command: gem -v
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: We need sqlite
          command: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      - ruby/install-deps:
          key: brisket
      - node/install-packages:
          cache-version: stringy-brisket
          pkg-manager: yarn
      - run:
          name: webpacker compile
          command: rake webpacker:compile
      - run:
          name: migrations
          command: rails db:schema:load
      - run:
          name: run tests
          command: rake test
