version: 2.1
orbs:
  node: circleci/node@3.0.0 

commands:
  sayhello:
    description: "work dammit"
    parameters:
      key:
        type: string
        default: "crunchy"
    steps:
      - run:
          name: "fart"
          command: echo << paramaters.key >>
        

jobs:
  build:
    docker: 
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - sayhello
          key: "butt"
      - run:
          name: Which rubygems?
          command: gem -v
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: We need sqlite
          command: sudo apt-get update && sudo apt-get install -y libsqlite3-dev
      - run:
          name: configure bundler
          command: bundle config deployment true
      - node/install-yarn
      - node/install-packages:
          cache-version: stringy-brisket
          pkg-manager: yarn
      - run:
          name: webpacker compile
          command: rake webpacker:compile
      - run:
          name: migrations
          command: rails db:schema:load
      - run:
          name: run tests
          command: rake test
