version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: ruby:2.7
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which rubygems?
          command: gem -v
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: is there a named step for this?
          command: rake test
