version: "3.2"
services:
  app:
    user: developer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
    working_dir: /workspace
    command: sleep infinity
    environment:
      BUNDLE_PATH: vendor/bundle
      INTERFACE: "0.0.0.0"
    ports:
      - "3000:3000"