name: Test
env:
  RAILS_ENV: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install SQlite
      run: sudo apt-get -y install sqlite3 libsqlite3-dev
    - uses: actions/cache@v1
      with:
        path: vender/bundle
        key: bundle-use-ruby-ubuntu-latest-ruby-2.7-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-ubuntu-latest-ruby-2.7-
    - name: Assemble dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4
    - name: Yarn Fucking Install
      run: yarn install --silent --no-progress --no-audit --no-optional
    - name: Compile Webpacker
      run: bundle exec rails webpacker:compile
    - name: Load DB schema
      run: bundle exec rails db:schema:load
    - name: Run tests
      run: bundle exec rails test
